quarkus.quartz.store-type=ram

quarkus.index-dependency.casehub-engine.group-id=io.casehub
quarkus.index-dependency.casehub-engine.artifact-id=casehub-engine
quarkus.index-dependency.casehub-blackboard.group-id=io.casehub
quarkus.index-dependency.casehub-blackboard.artifact-id=casehub-engine-blackboard
quarkus.index-dependency.casehub-persistence-memory.group-id=io.casehub
quarkus.index-dependency.casehub-persistence-memory.artifact-id=casehub-persistence-memory
quarkus.index-dependency.scheduler-quartz.group-id=io.casehub
quarkus.index-dependency.scheduler-quartz.artifact-id=casehub-engine-scheduler-quartz

quarkus.arc.selected-alternatives=\
  io.casehub.persistence.memory.InMemoryCaseInstanceRepository,\
  io.casehub.persistence.memory.InMemoryCaseMetaModelRepository,\
  io.casehub.persistence.memory.InMemoryReactiveCaseMetaModelRepository,\
  io.casehub.persistence.memory.InMemoryEventLogRepository
