quarkus.index-dependency.memory.group-id=io.casehub
quarkus.index-dependency.memory.artifact-id=casehub-persistence-hibernate

quarkus.quartz.clustered=false
quarkus.quartz.store-type=jdbc-cmt
quarkus.quartz.table-prefix=QRTZ_
quarkus.quartz.misfire-policy.task-job=ignore-misfire-policy