/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The version of the DSL used by the CaseHub.
 */
export type CaseHubDSL = string;
/**
 * Inbound connector message to typed case signal mappings.
 */
export type CaseInboundMappings = InboundSignalMapping[];
/**
 * Label evaluation rules for case queue management.
 */
export type CaseLabelRules = LabelRule[];
/**
 * Operational classification labels — hierarchical path strings via Path.parse().
 */
export type CaseHubLabels = string[];
/**
 * The CaseHub's name.
 */
export type CaseHubName = string;
/**
 * The CaseHub's namespace.
 */
export type CaseHubNamespace = string;
/**
 * Typed signal declarations for this case definition.
 */
export type CaseSignals = {
  name: string;
  contextType: string;
  [k: string]: unknown;
}[];
/**
 * The CaseHub's Markdown summary.
 */
export type CaseHubSummary = string;
/**
 * The CaseHub's title.
 */
export type CaseHubTitle = string;
/**
 * Behavioral type classifications — hierarchical path strings via Path.parse().
 */
export type CaseHubTypes = string[];
/**
 * The CaseHub's semantic version.
 */
export type CaseHubVersion = string;
export type Binding = {
  /**
   * Conflict resolution strategy for output merging. Default: LAST_WRITER_WINS.
   */
  conflictResolverStrategy?: "LAST_WRITER_WINS" | "FIRST_WRITER_WINS" | "FAIL" | "DEEP_MERGE";
  /**
   * Input channel name for Exchange data flow.
   */
  consumes?: string;
  contextWrite?: {
    [k: string]: unknown;
  };
  /**
   * Alternative capability names activated on primary node failure.
   */
  contingency?: string[];
  /**
   * TRANSIENT (fire-and-forget), PERSISTENT (long-running), or REINVOKED (re-invoked with state).
   */
  executionMode?: "TRANSIENT" | "PERSISTENT" | "REINVOKED";
  inputProjectionOverride?: string;
  /**
   * Worker lifetime scope: BINDING (single dispatch), COMPOUND, or CASE.
   */
  lifecycleScope?: "BINDING" | "COMPOUND" | "CASE";
  /**
   * Binding name — unique within the definition.
   */
  name?: string;
  on: Trigger;
  outcomePolicy?: OutcomePolicy;
  /**
   * PARTICIPANT blocks completion; COMPANION is a sidecar excluded from completion.
   */
  participation?: "PARTICIPANT" | "COMPANION";
  /**
   * Declared worker actions for rights classification.
   */
  permissionIntent?: string[];
  /**
   * Context keys this binding is expected to produce — used for expectation validation.
   */
  producedKeys?: string[];
  /**
   * Output channel name for Exchange data flow.
   */
  produces?: string;
  /**
   * Expression string or per-expression language override map. Plain string uses the definition-level expressionLang. Map syntax overrides: { jq: ".expr" } or { mvel: "expr" }.
   */
  when?:
    | string
    | {
        [k: string]: string;
      };
  capability?: string;
  subCase?: SubCase;
  humanTask?: HumanTask;
  /**
   * Context signal payload. Written to the case context when the binding fires. No worker dispatch.
   */
  signal?: {
    [k: string]: unknown;
  };
  /**
   * Hint for plan adaptation: always, conditional, or never.
   */
  replanAfter?: "always" | "conditional" | "never";
  exchangeProjection?:
    | string
    | {
        strategy: string;
        expression?: string;
        [k: string]: unknown;
      };
  [k: string]: unknown;
} & Binding1;
/**
 * Trigger condition that activates this binding.
 */
export type Trigger = {
  contextChange?: ContextChangeTrigger;
  cloudEvent?: CloudEventTrigger;
  schedule?: ScheduleTrigger;
  scopeActivated?: ScopeActivatedTrigger;
  [k: string]: unknown;
} & {
  [k: string]: unknown;
};
/**
 * Expression string or per-expression language override map. Plain string uses the definition-level expressionLang. Map syntax overrides: { jq: ".expr" } or { mvel: "expr" }.
 */
export type ExpressionOrOverride =
  | string
  | {
      [k: string]: string;
    };
/**
 * Fires on matching CloudEvents.
 */
export type CloudEventTrigger =
  | string
  | {
      type: string;
      source?: string;
      subject?: string;
      filter?: ExpressionOrOverride;
    };
/**
 * Time-based trigger.
 */
export type ScheduleTrigger = {
  cron?: string;
  every?: string;
  timezone?: string;
} & ScheduleTrigger1;
export type ScheduleTrigger1 = {
  [k: string]: unknown;
};
/**
 * A binding target that creates a WorkItem in casehub-work and resumes the case when the WorkItem reaches a terminal state.
 */
export type HumanTask = {
  title?: string;
  titleExpression?: string;
  templateRef?: string;
  inputMapping?: string;
  outputMapping?: string;
  scope?: string;
  scopeExpression?: string;
  candidateGroups?: string[] | string;
  candidateUsers?: string[] | string;
  expiresIn?: string;
  expiresInExpression?: string;
  claimDeadlineHours?: number;
  expiresAtExpression?: string;
  outcomes?: string[];
  payloadType?: string;
  resolutionType?: string;
  [k: string]: unknown;
} & HumanTask1;
export type HumanTask1 = {
  [k: string]: unknown;
};
export type Binding1 = {
  [k: string]: unknown;
};
export type CapabilityName = string;
export type GoalExpression = {
  /**
   * @minItems 1
   */
  allOf?: [string | GoalExpression, ...(string | GoalExpression)[]];
  /**
   * @minItems 1
   */
  anyOf?: [string | GoalExpression, ...(string | GoalExpression)[]];
  [k: string]: unknown;
} & GoalExpression1;
export type GoalExpression1 = {
  [k: string]: unknown;
};
/**
 * Unique milestone name within the definition.
 */
export type MilestoneName = string;
/**
 * Expression string or per-expression language override map. Plain string uses the definition-level expressionLang. Map syntax overrides: { jq: ".expr" } or { mvel: "expr" }.
 */
export type MilestoneCondition =
  | string
  | {
      [k: string]: string;
    };
export type WorkerName = string;
/**
 * @minItems 1
 */
export type WorkerCapabilities = [string, ...string[]];
/**
 * Code generation directive — ensures AgentModel type is generated by jsonschema2pojo. Not a user-facing property.
 */
export type AgentModel = {
  openai?: OpenAiModel;
  ollama?: OllamaModel;
  anthropic?: AnthropicModel;
  mistralAi?: MistralAiModel1;
  googleAiGemini?: GoogleAiGeminiModel1;
  [k: string]: unknown;
} & {
  [k: string]: unknown;
};
export type AgentModel1 = {
  openai?: OpenAiModel;
  ollama?: OllamaModel;
  anthropic?: AnthropicModel;
  mistralAi?: MistralAiModel1;
  googleAiGemini?: GoogleAiGeminiModel1;
  [k: string]: unknown;
} & AgentModel2;
export type AgentModel2 = {
  [k: string]: unknown;
};
export type ExpressionLang = string;
export type ContextType = string;

export interface CaseHub {
  dsl: CaseHubDSL;
  inboundMappings?: CaseInboundMappings;
  labelRules?: CaseLabelRules;
  labels?: CaseHubLabels;
  name: CaseHubName;
  namespace: CaseHubNamespace;
  semanticData?: {
    [k: string]: unknown;
  };
  signals?: CaseSignals;
  summary?: CaseHubSummary;
  title?: CaseHubTitle;
  types?: CaseHubTypes;
  use?: Use;
  version: CaseHubVersion;
  spec: CaseDefinitionSpec;
  episodic?: {
    memory?: {
      domain: string;
      entityId: string;
      recent?: number;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  expressionLang?: ExpressionLang;
  contextType?: ContextType;
  layers?: {
    name: string;
    [k: string]: unknown;
  }[];
  context?: {
    storeFactory?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface InboundSignalMapping {
  connectorType: string;
  correlation: string;
  correlationResolver?: string;
  payload: string;
  signal: string;
  [k: string]: unknown;
}
export interface LabelRule {
  /**
   * @minItems 1
   */
  actions: [
    (
      | {
          [k: string]: unknown;
        }
      | {
          [k: string]: unknown;
        }
    ),
    ...(
      | {
          [k: string]: unknown;
        }
      | {
          [k: string]: unknown;
        }
    )[]
  ];
  name: string;
  when: string;
  [k: string]: unknown;
}
/**
 * Declares external dependencies (secrets, config maps) required by this Case definition.
 */
export interface Use {
  configMaps?: string[];
  secrets?: string[];
  [k: string]: unknown;
}
/**
 * Case definition specification. unevaluatedProperties is true because the spec is an extension point.
 */
export interface CaseDefinitionSpec {
  /**
   * Agent routing strategy ID. Selects which worker instance handles a task.
   */
  agentRouting?: string;
  authorization?: Authorization;
  /**
   * Bindings connect trigger conditions to worker capabilities.
   */
  bindings?: Binding[];
  /**
   * Candidate matching strategy ID. Built-in: "exact", "subsumption".
   */
  candidateMatching?: string;
  /**
   * Capabilities define what Workers can do — declared competences with input/output contracts.
   */
  capabilities?: Capability[];
  /**
   * Typed streaming channels for worker-to-worker data flow.
   */
  channels?: {
    name: string;
    recordType: string;
    transport?: string;
    scope?: "COMPOUND" | "CASE";
    [k: string]: unknown;
  }[];
  completion?: CaseCompletion;
  /**
   * HTN decomposition strategy ID. Default: "identity".
   */
  decompositionStrategy?: string;
  /**
   * Default M-of-N multi-party approval configuration for action gates.
   */
  defaultQuorum?: {
    instances: number;
    required: number;
    onThresholdReached?: "KEEP" | "CANCEL";
    allowSameAssignee?: boolean;
    [k: string]: unknown;
  };
  /**
   * Desired end-states expressed as predicates over the CaseContext.
   */
  goals?: Goal[];
  /**
   * GOAP action declarations for planning.
   */
  goapActions?: {
    name: string;
    preconditions?: {
      [k: string]: boolean;
    };
    effects: {
      [k: string]: boolean;
    };
    cost?: number;
    benefit?: number;
    softPreconditions?: {
      [k: string]: boolean;
    };
    [k: string]: unknown;
  }[];
  /**
   * Declarative rules for humanTask candidate filtering and scoring.
   */
  humanTaskContextConstraints?: {
    when: ExpressionOrOverride;
    effect: {
      preferGroups?: string[];
      preferUsers?: string[];
      excludeGroups?: string[];
      excludeUsers?: string[];
      [k: string]: unknown;
    };
    weight?: number;
    [k: string]: unknown;
  }[];
  /**
   * HumanTask routing strategy ID. Enriches candidate sets with historical data.
   */
  humanTaskRouting?: string;
  /**
   * Workload-based constraints for humanTask candidate filtering.
   */
  humanTaskWorkloadConstraint?: {
    maxActiveTaskCount?: number;
    loadBalanceWeight?: number;
    [k: string]: unknown;
  };
  /**
   * Implementation routing strategy ID. Selects which binding(s) handle a capability.
   */
  implementationRouting?: string;
  /**
   * Maximum adaptation count per compound before Concede. Default: 5.
   */
  maxAdaptations?: number;
  /**
   * Maximum nesting depth for dynamic decomposition. Default: 3.
   */
  maxDecompositionDepth?: number;
  /**
   * Per-case memory retrieval configuration.
   */
  memoryRetrieval?: {
    enabled?: boolean;
    maxMemories?: number;
    domains?: string[];
    [k: string]: unknown;
  };
  /**
   * Observable progress markers derived from CaseContext.
   */
  milestones?: Milestone[];
  /**
   * Per-case resource constraints for decomposition and pattern execution.
   */
  planningConstraints?: {
    /**
     * ISO-8601 Duration (e.g. PT30M).
     */
    timeBudget?: string;
    resourceLimit?: number;
    weights?: {
      [k: string]: number;
    };
    costBudgets?: {
      [k: string]: number;
    };
    [k: string]: unknown;
  };
  /**
   * Planning strategy ID. Built-in: "default" (choreography), "sequential".
   */
  planningStrategy?: string;
  /**
   * Cascading decomposition strategy configuration.
   */
  portfolioConfig?: {
    delegates?: string[];
    timeouts?: {
      [k: string]: number;
    };
    [k: string]: unknown;
  };
  /**
   * Per-case multi-level recovery configuration.
   */
  recoveryPolicy?: {
    maxRetries?: number;
    maxRerouteAttempts?: number;
    classifierId?: string;
    revisionStrategyId?: string;
    replanStrategyId?: string;
    enabled?: boolean;
    [k: string]: unknown;
  };
  routingSignalWeights?: {
    [k: string]: number;
  };
  /**
   * Map of worker name to service account ID for tenant-specific endpoint resolution.
   */
  workerServiceAccountIds?: {
    [k: string]: string;
  };
  /**
   * Autonomous participants that observe CaseContext, make local decisions, and perform work.
   */
  workers?: Worker[];
  cbr?: Cbr;
  /**
   * Per-case reflection trigger configuration.
   */
  reflection?: {
    enabled?: boolean;
    importanceThreshold?: number;
    maxUnreflectedOutcomes?: number;
    maxSourceMemories?: number;
    importanceWeights?: {
      [k: string]: number;
    };
    [k: string]: unknown;
  };
  /**
   * Per-case expectation tracking configuration.
   */
  monitoring?: {
    enabled?: boolean;
    perCompletionThreshold?: number;
    windowSize?: number;
    [k: string]: unknown;
  };
  /**
   * Per-case plan adaptation configuration. String preset or explicit object.
   */
  adaptation?:
    | ("adaptive" | "conservative" | "off" | "progress")
    | {
        trigger?: string;
        optimization?: string;
        revision?: string;
        threshold?: number;
        metaReasoner?: string;
        repair?: string;
        contingencyThreshold?: number;
        [k: string]: unknown;
      };
  _codegenMistral?: MistralAiModel;
  _codegenGoogleAi?: GoogleAiGeminiModel;
  _codegenAgentModel?: AgentModel;
  _codegenAgent?: Agent;
  _codegenOpenAi?: OpenAiModel1;
  _codegenAnthropic?: AnthropicModel1;
  _codegenOllama?: OllamaModel1;
  [k: string]: unknown;
}
/**
 * ACL grants created when a case of this type is started.
 */
export interface Authorization {
  read?: string[];
  write?: string[];
  admin?: string[];
  claim?: string[];
  [k: string]: unknown;
}
export interface ContextChangeTrigger {
  filter?: ExpressionOrOverride;
  listenLayer?: string;
}
export interface ScopeActivatedTrigger {}
/**
 * How to handle worker decline, failure, and expiration outcomes.
 */
export interface OutcomePolicy {
  maxRerouteAttempts?: number;
  onDecline?: "REROUTE" | "FAULT";
  onExpired?: "REROUTE" | "FAULT";
  onFailure?: "REROUTE" | "FAULT";
  [k: string]: unknown;
}
export interface SubCase {
  namespace: string;
  name: string;
  version: string;
  completionStrategy?: "DEFAULT" | "CUSTOM";
  waitForCompletion?: boolean;
  inputMapping?: string;
  outputMapping?: string;
  maxRecursionDepth?: number;
  groupId?: string;
  totalInGroup?: number;
  requiredCount?: number;
  onThresholdReached?: "KEEP" | "CANCEL";
  [k: string]: unknown;
}
export interface Capability {
  description?: string;
  inputProjection?: string;
  name: CapabilityName;
  outputProjection?: string;
  cognitiveDemand?: {
    [k: string]: number;
  };
  [k: string]: unknown;
}
/**
 * Defines when a Case is terminally completed or failed based on Goal satisfaction.
 */
export interface CaseCompletion {
  /**
   * Expression string or per-expression language override map. Plain string uses the definition-level expressionLang. Map syntax overrides: { jq: ".expr" } or { mvel: "expr" }.
   */
  doneWhen?:
    | string
    | {
        [k: string]: string;
      };
  [k: string]: GoalExpression;
}
export interface Goal {
  /**
   * Expression string or per-expression language override map. Plain string uses the definition-level expressionLang. Map syntax overrides: { jq: ".expr" } or { mvel: "expr" }.
   */
  condition:
    | string
    | {
        [k: string]: string;
      };
  /**
   * Human-readable goal description.
   */
  description?: string;
  /**
   * Goal kind label — built-in: "success", "failure". Custom kinds require explicit status.
   */
  kind?: string;
  /**
   * Unique goal name within the definition.
   */
  name: string;
  [k: string]: unknown;
}
export interface Milestone {
  /**
   * Human-readable milestone description.
   */
  description?: string;
  /**
   * Expression string or per-expression language override map. Plain string uses the definition-level expressionLang. Map syntax overrides: { jq: ".expr" } or { mvel: "expr" }.
   */
  entryCriteria?:
    | string
    | {
        [k: string]: string;
      };
  name: MilestoneName;
  /**
   * SLA duration — ISO-8601 format. Fires timeout when exceeded.
   */
  slaDuration?: string;
  /**
   * When the SLA clock starts. Default: MILESTONE_ACTIVATED.
   */
  slaStartFrom?: "CASE_CREATED" | "MILESTONE_ACTIVATED" | "PREVIOUS_MILESTONE_COMPLETED" | "EVENT_OCCURRED";
  condition: MilestoneCondition;
  [k: string]: unknown;
}
export interface Worker {
  name: WorkerName;
  description?: string;
  capabilities: WorkerCapabilities;
  executionPolicy?: ExecutionPolicy;
  sequence?: string[];
  contextType?: string;
  outputType?: string;
  cost?: number;
  effect?: {
    [k: string]: boolean;
  };
  softDependency?: string[];
  [k: string]: unknown;
}
export interface ExecutionPolicy {
  timeoutMs?: number;
  retries?: RetryPolicy;
  [k: string]: unknown;
}
export interface RetryPolicy {
  maxAttempts?: number;
  delayMs?: number;
  [k: string]: unknown;
}
export interface Cbr {
  features: {
    [k: string]: string;
  };
  weights?: {
    [k: string]: number;
  };
  topK?: number;
  minSimilarity?: number;
  vectorWeight?: number;
  domain?: string;
  caseType?: string;
  cbrType?: string;
  timing?: "per-evaluation" | "case-lifetime";
  temporalDecayHalfLifeDays?: number;
  minCostSamples?: number;
  [k: string]: unknown;
}
/**
 * Code generation directive — ensures MistralAiModel type is generated by jsonschema2pojo. Not a user-facing property.
 */
export interface MistralAiModel {
  apiKey?: string;
  modelName: string;
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  baseUrl?: string;
  [k: string]: unknown;
}
/**
 * Code generation directive — ensures GoogleAiGeminiModel type is generated by jsonschema2pojo. Not a user-facing property.
 */
export interface GoogleAiGeminiModel {
  apiKey?: string;
  modelName: string;
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  topK?: number;
  [k: string]: unknown;
}
export interface OpenAiModel {
  apiKey?: string;
  modelName: string;
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  frequencyPenalty?: number;
  presencePenalty?: number;
  organizationId?: string;
  baseUrl?: string;
  [k: string]: unknown;
}
export interface OllamaModel {
  baseUrl: string;
  modelName: string;
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  topK?: number;
  [k: string]: unknown;
}
export interface AnthropicModel {
  apiKey?: string;
  modelName: string;
  version?: string;
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  topK?: number;
  baseUrl?: string;
  [k: string]: unknown;
}
export interface MistralAiModel1 {
  apiKey?: string;
  modelName: string;
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  baseUrl?: string;
  [k: string]: unknown;
}
export interface GoogleAiGeminiModel1 {
  apiKey?: string;
  modelName: string;
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  topK?: number;
  [k: string]: unknown;
}
/**
 * Code generation directive — ensures Agent type is generated by jsonschema2pojo. Not a user-facing property.
 */
export interface Agent {
  systemPrompt: string;
  inputProjection: string;
  outputProjection: string;
  userMessageTemplate?: string;
  model: AgentModel1;
  [k: string]: unknown;
}
/**
 * Code generation directive — ensures OpenAiModel type is generated by jsonschema2pojo. Not a user-facing property.
 */
export interface OpenAiModel1 {
  apiKey?: string;
  modelName: string;
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  frequencyPenalty?: number;
  presencePenalty?: number;
  organizationId?: string;
  baseUrl?: string;
  [k: string]: unknown;
}
/**
 * Code generation directive — ensures AnthropicModel type is generated by jsonschema2pojo. Not a user-facing property.
 */
export interface AnthropicModel1 {
  apiKey?: string;
  modelName: string;
  version?: string;
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  topK?: number;
  baseUrl?: string;
  [k: string]: unknown;
}
/**
 * Code generation directive — ensures OllamaModel type is generated by jsonschema2pojo. Not a user-facing property.
 */
export interface OllamaModel1 {
  baseUrl: string;
  modelName: string;
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  topK?: number;
  [k: string]: unknown;
}
